### ISSUE TITLE
进入到分析界面发现没有视频播发

### ISSUE THREAD

**Issue by heart6622** [Ujs-lj/web_final#2]
![image](https://user-images.githubusercontent.com/91278105/186485264-f5aa0054-faf1-4cf9-b8cf-21c3a3be10c3.png)
![image](https://user-images.githubusercontent.com/91278105/186485340-8b3184e8-010e-45f2-97df-e2c8daca21e2.png)
返回值一直为200

**Comment by JerryAuas** [comment]
把视频地址换成你自己的然后重新创建一save_img文件夹
